Preparing stuff for move to github
Ignore-this: 10b4e09621047b24878b0b0ac0f298a2

darcs-hash:09de3ab51d184fc37007aab4f5fbe72c3ff38426

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,42 +1,92 @@
+# <http://docs.travis-ci.com/user/languages/haskell/>
+# <https://github.com/ZeusWPI/12Urenloop/blob/master/.travis.yml>
+# <http://docs.travis-ci.com/user/build-configuration/>
+# The only versions natively supported by TravisCI are (7.0, 7.4,
+# 7.6, 7.8). Other versions (6.8, 6.10, 6.12; 7.2; 7.10) are not
+# supported, and patchlevels cannot be secified.
+# <http://docs.travis-ci.com/user/ci-environment/#Haskell-VM-images>
+#
+# So instead, we use <https://github.com/hvr/multi-ghc-travis>
+# However, note that these are only for Ubuntu Linux 12.04 LTS
+# 64-bit. Will have to come up with something fancy in order to
+# also use the native versions for testing Windows and OSX.
 env:
- - GHCVER=6.8.2
- - GHCVER=6.10.1
- - GHCVER=6.12.1
- - GHCVER=6.12.3
- - GHCVER=7.0.1
- - GHCVER=7.0.2
- - GHCVER=7.0.3
- - GHCVER=7.0.4
- - GHCVER=7.2.1
- - GHCVER=7.2.2
- - GHCVER=7.4.1
- - GHCVER=7.4.2
- - GHCVER=7.6.1
- - GHCVER=7.6.2
- - GHCVER=7.6.3
- - GHCVER=7.8.0
- - GHCVER=7.8.3
- - GHCVER=7.10.1
+ - CABALVER=1.16 GHCVER=6.12.3
+ - CABALVER=1.16 GHCVER=7.0.1
+ - CABALVER=1.16 GHCVER=7.0.2
+ - CABALVER=1.16 GHCVER=7.0.3
+ - CABALVER=1.16 GHCVER=7.0.4
+ - CABALVER=1.16 GHCVER=7.2.1
+ - CABALVER=1.16 GHCVER=7.2.2
+ - CABALVER=1.16 GHCVER=7.4.1
+ - CABALVER=1.16 GHCVER=7.4.2
+ - CABALVER=1.16 GHCVER=7.6.1
+ - CABALVER=1.16 GHCVER=7.6.2
+ - CABALVER=1.18 GHCVER=7.6.3
+ - CABALVER=1.18 GHCVER=7.8.1
+ - CABALVER=1.18 GHCVER=7.8.2
+ - CABALVER=1.18 GHCVER=7.8.3
+ - CABALVER=1.18 GHCVER=7.8.4
+ - CABALVER=1.22 GHCVER=7.10.1
+ - CABALVER=1.22 GHCVER=7.10.2 # (pre-release snapshot)
 
+
+# Rather than using the version suggested by hvr/multi-ghc-travis,
+# we use the version from lens
+# <https://github.com/ekmett/lens/blob/master/.travis.yml>
 before_install:
- - sudo add-apt-repository -y ppa:hvr/ghc
- - sudo apt-get update
- - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
- - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+  # If $GHCVER is the one travis has, don't bother reinstalling it.
+  # We can also have faster builds by installing some libraries with
+  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
+  # with cabal-1.18.
+  - |
+    if [ $GHCVER = `ghc --numeric-version` ]; then
+      # Try installing some of the build-deps with apt-get for speed.
+      travis/cabal-apt-install --enable-tests $MODE
+      export CABAL=cabal
+    else
+      # Install the GHC we want from hvr's PPA
+      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+      travis_retry sudo apt-get update
+      travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+      export CABAL=cabal-$CABALVER
+      export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+    fi
+  # Uncomment whenever hackage is down.
+  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
+  - $CABAL update
 
 install:
- - cabal-1.18 update
- - if [ "$GHCVER" = "6.12.3" ]; then
-      cabal-1.18 install --only-dependencies;
-      cabal-1.18 install 'QuickCheck==2.6.*';
-   else
-      cabal-1.18 install --only-dependencies --enable-tests;
-   fi
+ - $CABAL --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry $CABAL update
+ - $CABAL install --only-dependencies --enable-tests --enable-benchmarks
+ - $CABAL configure --enable-tests --enable-benchmarks -v2
 
+
+# Here starts the actual work to be performed for the package under
+# test; any command which exits with a non-zero exit code causes
+# the build to fail.
 script:
- - cd test/ && runghc ./GenTests.hs && cd ..
- - cabal-1.18 configure --enable-tests -v2
- - cabal-1.18 build
- - cabal-1.18 test
- - cabal-1.18 check
- - cabal-1.18 sdist
+  - $CABAL build
+  - $CABAL test --show-details=always
+  - $CABAL test
+  - $CABAL check
+  # tests that a source-distribution can be generated
+  - $CABAL sdist
+  # check that the generated source-distribution can be built & installed
+  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+    cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+       cabal install --force-reinstalls "$SRC_TGZ";
+    else
+       echo "expected '$SRC_TGZ' not found";
+       exit 1;
+    fi
+
+# TODO: additional checks:
+# * Check for code-smell via hlint
+# * Check for build-depends excluding latest package versions with packdeps
+# * Check for unused build-depends with packunused
+# * Check for 100% Haddock coverage
+# * Check for trailing whitespaces and/or tabs in source files
